---
driver:
  name: vagrant
  require_chef_omnibus: 12.4.1
  customize:
    memory: 1024

provisioner:
  name: chef_zero
  environments_path: '../chef-repo/environments'
  data_bags_path: '../chef-repo/data_bags'

platforms:
  - name: centos-7.0
    driver_config:
      network:
        - ["private_network", {ip: "33.33.11.10"}]

suites:
  - name: jenkins-server
    provisioner:
      client_rb:
        environment: production
      solo_rb:
        environment: production
    driver:
      vm_hostname: jenkins-server001.local
      network:
        - ["private_network", {ip: "33.33.11.170"}]
    run_list: 'recipe[jenkins-server]'
    attributes:
      dev_mode: true
      jenkins-server:
        slaves:
          enable: true
